module Queries
  class NewCommentMailer < BaseQuery
    def self.description: (String) -> untyped
    def self.field: (:response, String, null: false) -> untyped
    def self.type: (untyped, null: false) -> untyped
  end
end
